### ISSUE TITLE
Tezuka et al. - 2021 - Real-time, automatic, open-source sleep stage classification system using single EEG for mice

### ISSUE THREAD

**Issue by gsaurabhr** [csndl-iitd/realtime-sleep-staging#2]
Read this paper and discuss key takeaways for our project here.

**Comment by Ayush-Tibrewal** [comment]
### Quick Summary of this paper
-  The researchers developed a system to automatically and accurately classify sleep stages in mice using data from **a single EEG (electroencephalogram) channel.** This system can identify whether a mouse is awake, in non-REM (NREM) sleep, or in rapid eye movement (REM) sleep in real-time. 
-  The researchers used 214 recordings, each 6 hours long, with sleep stages annotated by human experts.The system processes data in 10-second epochs.
- **The researchers created two systems: UTSN (Universal Time-Series Network) and UTSN-L (UTSN with Long Short-Term Memory).**
- UTSN uses a convolutional neural network (CNN) to process raw EEG data, FFT (Fast Fourier Transformation) data, and zeitgeber time (ZT), which relates to the circadian rhythm.
- UTSN-L adds a Long Short-Term Memory (LSTM) network to consider past data, improving accuracy.
- The systems were evaluated against conventional methods like logistic regression, random forest, and AdaBoost.Metrics used for evaluation included sensitivity, accuracy, precision, F1 score, and Matthews Correlation Coefficient (MCC).UTSN-L performed better overall, especially for detecting REM sleep.
- UTSN-L (UTSN with Long Short-Term Memory) The overall accuracy was 90% For REM sleep detection, UTSN-L achieved 91% sensitivity and 98% specificity.
